#!/bin/bash
set -e

# include dot-files (if present) when coping into mounted volumes
shopt -s dotglob

# if empty, copy apache2 configuration to volume
if [ ! "$(ls -A /etc/apache2)" ]; then
    cp -r  /usr/local/etc/apache2/* /etc/apache2
    echo "[info] copied apache2 configuration directory"
fi

# if Concrete5 is not yet installed, copy it into web root
if [ ! -e '/var/www/html/concrete/config/concrete.php' ]; then
    cd /var/www/html/
    if [ "$(ls -A /var/www/html)" ]; then
        echo "[warn] /var/www/html/ is not Empty. It contains:" 1>&2
        ls -A 1>&2
    fi
    echo "[info] Concrete5 Version: ${CONCRETE5_VERSION}"
    cp -r /usr/local/src/concrete5-${CONCRETE5_VERSION}/* /var/www/html

    # change required permissions incl. for multi-lingual sites
    chown -Rv root:www-data application/files/
    chmod -Rv 775 application/files/
    chown -Rv root:www-data application/config/
    chmod -Rv 775 application/config/
    chown -Rv root:www-data packages/
    chmod -Rv 775 packages/
    chown -Rv root:www-data updates/
    chmod -Rv 775 updates/
    mkdir -v  application/languages/site
    chown -Rv root:www-data application/languages/site
    chmod -Rv 775 application/languages/site
    echo "[info] copied Concrete5.7 and set permissions"
fi

# else default to run whatever the user wanted like "bash"
exec "$@"
